/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\RoboAzulModel.glb -o src\scratch\RoboAzul.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RoboAzulModel.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[71.086, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2003.geometry} material={materials['palette.003']} position={[4.143, 0, 4.2]} />
        <mesh geometry={nodes.Object_2004.geometry} material={materials['palette.003']} position={[-4.013, 0, 3.87]} />
        <mesh geometry={nodes.Object_2006.geometry} material={materials['palette.003']} position={[0, 0, 1.131]} />
        <mesh geometry={nodes.Object_2007.geometry} material={materials['palette.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/RoboAzulModel.glb')
