/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\RoboNPCModel.glb -o src\scratch\RoboNPC.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RoboNPCModel.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[60.702, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CabeçaRoboBranco.geometry} material={materials['palette.004']} position={[-60.81, 0, 1.186]} />
        <mesh geometry={nodes.MaoDireitaRoboBranco.geometry} material={materials['palette.004']} position={[-63.445, 0, 4]} />
        <mesh geometry={nodes.MaoEsquerdaRoboBranco.geometry} material={materials['palette.004']} position={[-57.529, 0, 4]} />
        <mesh geometry={nodes.TroncoRoboBranco.geometry} material={materials['palette.004']} position={[-60.81, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/RoboNPCModel.glb')
